name: sd-benchmarking
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - matplotlib
  - biopython
  - blast>=2.15
  - mafft>=7.5
  - muscle>=5
  - prank
  - iqtree>=3
  - gffread
  - bedtools
  - samtools
